apps/estoque/urls.py
from django.urls import path, include
from apps.estoque.views import *


entrada_patterns = [
    path('listar/', ListEntradaEstoque.as_view(), name='listar_entrada_estoque'),
    path('', entrada_estoque, name='entrada_estoque'),
]

saida_patterns = [
    path('listar/', ListSaidaEstoque.as_view(), name='listar_saida_estoque'),
    path('', saida_estoque, name='saida_estoque'),
]

urlpatterns = [
    path('estoque/entrada/', include(entrada_patterns)),
    path('estoque/saida/', include(saida_patterns)),
    path('detalhar/<int:pk>/', EstoqueDetail.as_view(), name='detalhar_entrada_saida'),
    path('venda/pendente/atualizar/<int:pk>/', pagamento_pendente, name='atualizar_venda'),
    path('venda/pendente/', listar_venda_pendente, name='listar_venda'),
    path('entrega/pendente/atualizar/<int:pk>/', entrega_pendente, name='atualizar_entrega'),
    path('entrega/pendente/', listar_entrega, name='listar_entrega'),
]

segfer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.autenticacao.urls')),
    path('empresa/', include('apps.fornecedor.urls')),
    path('', include('apps.estoque.urls')),
    path('material/', include('apps.material.urls')),
    path('cliente/', include('apps.cliente.urls')),


]

apps/cliente/models.py
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.core.mail import send_mail, mail_admins

# Create your models here.


class Cliente(models.Model):
    nome = models.CharField(max_length=255, verbose_name='Nome:')
    cpf = models.CharField(max_length=100, verbose_name='CPF:', unique=True, blank=True, null=True)
    email = models.EmailField(max_length=255, verbose_name='E-mail:')
    telefone = models.CharField(max_length=50, verbose_name='Telefone Fixo:')
    celular = models.CharField(max_length=50, verbose_name='Celular/WhatsApp:')
    cep = models.CharField(max_length=100)
    logradouro = models.CharField(max_length=300, verbose_name='Logradouro:')
    numero = models.CharField(max_length=30, verbose_name='Número:')
    bairro = models.CharField(max_length=100, verbose_name='Bairro:')
    complemento = models.CharField(max_length=255, blank=True, null=True, verbose_name="Complemento:")
    cidade = models.CharField(max_length=200, verbose_name='Cidade:')
    estado = models.CharField(max_length=50, verbose_name='Estado:')


    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('listar_cliente')

apps/estoque/models.py
from django.db import models
import datetime

from django.urls import reverse
from apps.autenticacao.models import Usuario
from apps.cliente.models import Cliente
from apps.estoque.managers import EstoqueEntradaManager, EstoqueSaidaManager
from apps.material.models import MaterialEstoque


MOVIMENTO_CHOICES = (
    ('e', 'Entrada'),
    ('s', 'Saída'),
)

SITUACAO_COICHES = (
    ('pg', 'PAGO'),
    ('pend', 'PENDENTE')
)

SITUACAO_ENTREGA = (
    ('f', 'FINALIZADA'),
    ('p', 'PENDENTE')
)



class Estoque(models.Model):
    codigo = models.CharField(max_length=50, null=True, blank=True)
    data = models.DateTimeField(verbose_name=(
        'Data da Entrada:'), blank=True, null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name='Funcionário:')
    movimento = models.CharField(max_length=50, choices=MOVIMENTO_CHOICES, blank=True, verbose_name='Tipo de Evento:')
    valor_total = models.FloatField(blank=True, null=True, default=0)
    desconto = models.FloatField(blank=True, null=True, default=0)
    situacao = models.CharField(max_length=10, choices=SITUACAO_COICHES, verbose_name='Situação:')
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    entrega = models.BooleanField(blank=True, null=True, default=False)
    status_entrega = models.CharField(max_length=30, blank=True, null=True, choices=SITUACAO_ENTREGA, default='p')

    def get_absolute_url(self):
        return reverse('listar_material')

    def __str__(self):
        return self.codigo


class ItensEstoque(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
    material = models.ForeignKey(MaterialEstoque, on_delete=models.CASCADE)
    quantidade = models.FloatField(default=0)
    saldo = models.FloatField(blank=True, null=True)
    valor = models.FloatField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('listar_material')


class EstoqueEntrada(Estoque):

    objects = EstoqueEntradaManager()
    class Meta:
        proxy = True


class EstoqueSaida(Estoque):
    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True

apps/cliente/forms.py
from django import forms

from apps.cliente.models import Cliente


class ClienteForm(forms.ModelForm):
    cpf = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': 'true', 'data-mask': '000.000.000-00',
               'placeholder': '000.000.000-00'}), label="CPF:")

    telefone = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': 'true', 'data-mask': '(00) 0000-0000',
               'placeholder': '(00) 0000-0000'}), label="Telefone:")

    celular = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': 'true', 'data-mask': '(00) 00000-0000',
               'placeholder': '(00) 00000-0000'}), label="Celular:")

    cep = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'data-mask': '00000-000', 'placeholder': '00000-000'}),
        label='CEP:')
    class Meta:
        model = Cliente
        fields = ('nome', 'cpf', 'email', 'telefone', 'celular', 'cep', 'logradouro', 'numero',
                  'bairro', 'complemento', 'cidade', 'estado')

apps/estoque/forms.py
from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms

from apps.estoque.models import ItensEstoque, Estoque


class EstoqueEntradaForm(forms.ModelForm):

    data = forms.DateTimeField(widget=DateTimePickerInput(format='%d/%m/%Y %H:%M:%S'),
                                          label="Data da Entrada:")

    class Meta:
        model = Estoque
        fields = ('usuario', 'codigo', 'data', 'movimento', 'valor_total')
        widgets = {
            'valor_total': forms.TextInput(attrs={'class': 'form-control', 'required': 'true', 'readonly': 'readonly'}),
            'codigo': forms.TextInput(attrs={'class': 'form-control', 'required': 'true', 'readonly': 'readonly'}),
        }


class EstoqueSaidaForm(forms.ModelForm):

    data = forms.DateTimeField(widget=DateTimePickerInput(format='%d/%m/%Y %H:%M:%S'),
                                          label="Data da Entrada:")


    class Meta:
        model = Estoque
        fields = ('usuario', 'codigo', 'data', 'movimento', 'valor_total',
                  'desconto', 'situacao', 'cliente', 'entrega', 'status_entrega')
        widgets = {
            'codigo': forms.TextInput(attrs={'class': 'form-control', 'required': 'true', 'readonly': 'readonly'}),
            'valor_total': forms.TextInput(attrs={'required': 'true', 'readonly': 'readonly'}),
            'desconto': forms.NumberInput(attrs={'required': 'false'}),
            'cliente': forms.Select(attrs={'required': 'true'}),

            # 'data-live-search': 'true'
        }


class FormItensEstoqueEntrada(forms.ModelForm):

    class Meta:
        model = ItensEstoque
        fields = ['material', 'quantidade', 'saldo']
        exclude = ()
        widgets = {
            'material': forms.Select(attrs={'class': 'form-control', 'style': 'width:300px;', 'required': 'true'}),
            'quantidade': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'valor': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
        }


class FormItensEstoqueSaida(forms.ModelForm):

    class Meta:
        model = ItensEstoque
        fields = ['material', 'quantidade', 'saldo', 'valor', 'estoque']
        exclude = ()
        widgets = {
            'material': forms.Select(attrs={'class': 'form-control', 'style': 'width:300px;', 'required': 'true'}),
            'quantidade': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'valor': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
        }

apps/estoque/views.py
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url, redirect

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from apps.cliente.models import Cliente
from apps.estoque.forms import EstoqueEntradaForm, EstoqueSaidaForm, \
    FormItensEstoqueSaida, FormItensEstoqueEntrada
from apps.estoque.models import MaterialEstoque, Estoque, ItensEstoque, EstoqueEntrada, EstoqueSaida
from apps.estoque.uteis import Util


def dar_baixa_estoque(form):
    materiais = form.estoques.all()
    for item in materiais:
        material = MaterialEstoque.objects.get(pk=item.material.pk)
        material.estoque = item.saldo
        material.save()
    print('Estoque Atualizado com sucesso.')


@method_decorator([login_required], name='dispatch')
class ListEntradaEstoque(ListView):
    model = EstoqueEntrada
    template_name = "listar_entrada_estoque.html"
    context_object_name = "object_list"
    paginate_by = 10


#Função de Entrada de Estoque
def estoque_add(request, template_name, movimento, url):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(Estoque, ItensEstoque,
                                                 fields=['material', 'quantidade', 'saldo', 'valor'],
                                                 form=FormItensEstoqueEntrada, extra=1)
    if request.method == 'POST':
        form = EstoqueEntradaForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(request.POST, instance=estoque_form, prefix='estoque')
        if form.is_valid() and formset.is_valid():
            form = form.save(commit=False)
            form.movimento = movimento
            form.save()
            formset.save()
            dar_baixa_estoque(form)
            return {'pk': form.pk}
    else:
        form = EstoqueEntradaForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')
    context = {'form': form, 'formset': formset, 'codigoentrada': Util.geradorcodigovenda()}
    return context


@login_required
def entrada_estoque(request):
    template_name = "entrada_estoque.html"
    movimento = 'e'
    url = 'listar_entrada_estoque'
    context = estoque_add(request, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url))
    return render(request, template_name, context)


@method_decorator([login_required], name='dispatch')
class ListSaidaEstoque(ListView):
    model = EstoqueSaida
    template_name = "listar_saida_estoque.html"
    context_object_name = "object_list"
    paginate_by = 10

    def get_queryset(self):
        return EstoqueSaida.objects.all().order_by('-codigo')


#Função de Saida de Estoque
def saida_add(request, template_name, movimento, url):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(Estoque, ItensEstoque,
                                                 fields=['estoque', 'material', 'quantidade', 'saldo', 'valor'],
                                                 form=FormItensEstoqueSaida, extra=1)
    if request.method == 'POST':
        form = EstoqueSaidaForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(request.POST, instance=estoque_form, prefix='estoque')
        if form.is_valid() and formset.is_valid():
            form = form.save(commit=False)
            form.movimento = movimento
            form.save()
            formset.save()
            dar_baixa_estoque(form)
            return {'pk': form.pk}
    else:
        form = EstoqueSaidaForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')
    context = {'form': form, 'formset': formset, 'codigovenda': Util.geradorcodigovenda()}
    return context


@login_required
def saida_estoque(request):
    template_name = "saida_estoque.html"
    movimento = 's'
    url = 'index'
    context = saida_add(request, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url))
    return render(request, template_name, context)


@method_decorator([login_required], name='dispatch')
class EstoqueDetail(DetailView):
    model = Estoque
    template_name = 'detalhar_entrada_saida.html'


@login_required()
def pagamento_pendente(request, pk):
    es = EstoqueSaida.objects.get(pk=pk)
    es_form = EstoqueSaidaForm(request.POST or None, instance=es)
    if es_form.is_valid():
        es_form.save()
        return redirect(reverse('listar_venda'))
    return render(request, 'atualizar_venda.html', {
        'es_form': es_form,
        'es': es,
    })


@login_required()
def listar_venda_pendente(request):
    venda = EstoqueSaida.objects.all()
    cliente = Cliente.objects.all()
    return render(request, 'listar_venda_pendente.html', {'cliente': cliente, 'venda': venda})


@login_required()
def entrega_pendente(request, pk):
    es = EstoqueSaida.objects.get(pk=pk)
    cliente = Cliente.objects.filter(pk=es.cliente_id)
    es_form = EstoqueSaidaForm(request.POST or None, instance=es)
    if es_form.is_valid():
        es_form.save()
        return redirect(reverse('listar_entrega'))
    return render(request, 'atualizar_entrega.html', {
        'es_form': es_form,
        'es': es,
        'cliente': cliente
    })


@login_required()
def listar_entrega(request):
    cliente = Cliente.objects.all()
    venda = EstoqueSaida.objects.all()
    return render(request, 'listar_entrega_pendente.html', {'venda': venda, 'cliente': cliente})

apps/estoque/templates/atualizar_entrega.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}
{% block title %}Finalizar Entrega{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Detalhamento da Entrega</h1>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <div class="card-header">
        <h3 class="card-title">Dados da Venda</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-solid">
                    <div class="box-body">
                       <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    {{ es_form.cliente|bootstrap }}
                                </div>
                                <div class="col-md-3" hidden>
                                    <select name="movimento" id="id_movimento">
                                      <option value="s" selected="">Saída</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <label>Data da Venda:</label>
                                    {{ es_form.data }}
                                </div>
                                <div class="col-md-3" hidden>
                                    <select name="usuario" required="" id="id_usuario">
                                      <option value="{{ request.user.id }}" selected="">{{ request.user }}</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    {{ es_form.codigo|bootstrap }}
                                </div>
                                <div class="col-md-3">
                                    {{ es_form.valor_total|bootstrap }}
                                </div>
                                <div class="col-md-3">
                                    {{ es_form.desconto|bootstrap }}
                                </div>
                                <div class="col-md-3">
                                    {{ es_form.entrega|bootstrap }}
                                </div>
                                <div class="col-md-3" hidden>
                                    {{ es_form.situacao|bootstrap }}
                                </div>
                                <div class="col-md-3">
                                    {{ es_form.status_entrega|bootstrap }}
                                </div>
                            </div>
                           <br>
                       </fieldset>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <div class="card-header">
        <h3 class="card-title">Endereço da Entrega</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-solid">
                    <div class="box-body">
                        <fieldset>
                            {% for c in cliente %}
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_cep">CEP:</label>
                                        <div class=" ">
                                            <input type="text" name="cep" class="form-control form-control" value="{{ c.cep }}" data-mask="00000-000" placeholder="00000-000" required="" id="id_cep" maxlength="9" autocomplete="off"  readonly="true">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_logradouro">Logradouro:</label>
                                        <div class=" ">
                                            <input type="text" name="logradouro" maxlength="300" value="{{ c.logradouro }}" class=" form-control" required="" id="id_logradouro" readonly="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_numero">Número:</label>
                                        <div class=" ">
                                            <input type="text" name="numero" maxlength="30" value="{{ c.numero }}" class=" form-control" required="" id="id_numero" readonly="true">
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_bairro">Bairro:</label>
                                        <div class=" ">
                                            <input type="text" name="bairro" maxlength="100" value="{{ c.bairro }}" class=" form-control" required="" id="id_bairro" readonly="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_complemento">Complemento:</label>
                                        <div class=" ">
                                            {% if c.complemento == None %}
                                            <input type="text" name="complemento" maxlength="255" value="" class=" form-control" id="id_complemento" readonly="true">
                                            {% else %}
                                            <input type="text" name="complemento" maxlength="255" value="{{ c.complemento }}" class=" form-control" id="id_complemento" readonly="true">
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_cidade">Cidade:</label>
                                        <div class=" ">
                                            <input type="text" name="cidade" maxlength="200" value="{{ c.cidade }}" class=" form-control" required="" id="id_cidade" readonly="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-group">
                                        <label class="control-label  " for="id_estado">Estado:</label>
                                        <div class=" ">
                                            <input type="text" name="estado" maxlength="50" value="{{ c.estado }}" class=" form-control" required="" id="id_estado" readonly="true">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <div class="card-header">
        <h3 class="card-title">Matériais da Entrega</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-solid">
                    <div class="box-body">
                        <fieldset>
                        <div style="background: #ddd; border: 1px #A9A9A9 solid;">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Produto</th>
                              <th style="text-align: center;">Quantidade</th>
                              <th style="text-align: center;">Valor</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for item in es.estoques.all %}
                              <tr id="item">
                                <td>{{ item.material }}</td>
                                <td style="text-align: center;">{{ item.quantidade }}</td>
                                <td style="text-align: center;">{{ item.valor }}</td>
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                        </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <a href="{% url 'listar_entrega' %}" class="btn btn-outline-info">
                    <i class="fa fa-ban" aria-hidden="true"></i>
                    Cancelar
                </a>
            </div>
            <div class="col-lg-10" style="text-align: right;">
                <button type="submit" class="btn btn-outline-success" >
                    <i class="fa fa-check" aria-hidden="true"></i>
                    Salvar
                </button>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
</form>
<script src="{% static 'estaticos/dist/js/update_venda.js' %}"></script>
{% endblock content %}

apps/estoque/templates/listar_saida_estoque.html
{% extends 'base.html' %}
{% block title %}Lista de Vendas{% endblock %}
{% block content %}
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Lista de Vendas</h1>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <a href="{% url 'saida_estoque' %}" class="btn btn-outline-primary">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    Adicionar
                </a>
            </div>
            <div class="col-lg-10" style="text-align: right;">
                <div class="col-md-4 float-right">
                    <div class="input-group input-group">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Pesquisar">

                        <div class="input-group-append">
                          <button type="submit" class="btn btn-outline-primary"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-0">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Código</th>
                            <th>Cliente</th>
                            <th style=" text-align: center;">Data</th>
                            <th style=" text-align: center;">Situação</th>
                            <th style="width: 8%; text-align: center;">Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for saida in object_list %}
                            <tr>
                                <td>{{ saida.codigo }}</td>
                                <td>{{ saida.cliente }}</td>
                                <td style=" text-align: center;">{{ saida.data }}</td>
                                <td style=" text-align: center;">{{ saida.get_situacao_display }}</td>
                                <td style="width: 8%;" align="center">
                                    <a class="icons" href="{% url 'detalhar_entrada_saida' saida.pk %}" ><i class="fa fa-cubes" title="Detalhar"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
  </div>
</section>
{% include "parts/pagination.html" %}
{% endblock %}