apps/material/urls.py
from django.urls import path
from apps.material.views import material_json, ListMaterial, CreateMaterial, UpdateMaterial

urlpatterns = [
    path('', ListMaterial.as_view(), name='listar_material'),
    path('cadastrar/', CreateMaterial.as_view(), name='cadastrar_material'),
    path('atualizar/<int:pk>', UpdateMaterial.as_view(), name='atualizar_material'),
    path('<int:pk>/json/', material_json, name='material_json'),
]

segfer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('', include('apps.autenticacao.urls')),
    path('empresa/', include('apps.fornecedor.urls')),
    path('', include('apps.estoque.urls')),
    path('material/', include('apps.material.urls')),
    path('cliente/', include('apps.cliente.urls')),


]

apps/estoque/models.py
from django.db import models
import datetime

from django.urls import reverse
from apps.autenticacao.models import Usuario
from apps.cliente.models import Cliente
from apps.estoque.managers import EstoqueEntradaManager, EstoqueSaidaManager
from apps.material.models import MaterialEstoque


MOVIMENTO_CHOICES = (
    ('e', 'Entrada'),
    ('s', 'Saída'),
)

SITUACAO_COICHES = (
    ('pg', 'PAGO'),
    ('pend', 'PENDENTE')
)

SITUACAO_ENTREGA = (
    ('f', 'FINALIZADA'),
    ('p', 'PENDENTE')
)



class Estoque(models.Model):
    codigo = models.CharField(max_length=50, null=True, blank=True)
    data = models.DateTimeField(verbose_name=(
        'Data da Entrada:'), blank=True, null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name='Funcionário:')
    movimento = models.CharField(max_length=50, choices=MOVIMENTO_CHOICES, blank=True, verbose_name='Tipo de Evento:')
    valor_total = models.FloatField(blank=True, null=True, default=0)
    desconto = models.FloatField(blank=True, null=True, default=0)
    situacao = models.CharField(max_length=10, choices=SITUACAO_COICHES, verbose_name='Situação:')
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    entrega = models.BooleanField(blank=True, null=True, default=False)
    status_entrega = models.CharField(max_length=30, blank=True, null=True, choices=SITUACAO_ENTREGA, default='p')

    def get_absolute_url(self):
        return reverse('listar_material')

    def __str__(self):
        return self.codigo


class ItensEstoque(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
    material = models.ForeignKey(MaterialEstoque, on_delete=models.CASCADE)
    quantidade = models.FloatField(default=0)
    saldo = models.FloatField(blank=True, null=True)
    valor = models.FloatField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('listar_material')


class EstoqueEntrada(Estoque):

    objects = EstoqueEntradaManager()
    class Meta:
        proxy = True


class EstoqueSaida(Estoque):
    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True

apps/material/models.py
from django.db import models
from django.urls import reverse

from apps.fornecedor.models import EmpresaContratante


class MaterialEstoque(models.Model):
    codigo = models.CharField(max_length=100, unique=True)
    nome = models.CharField(max_length=100, verbose_name="Descrição")
    estoque = models.FloatField(default=0, verbose_name="Quantidade")
    preco = models.DecimalField(max_digits=6, decimal_places=2, default=0.0, verbose_name="Preço de Venda")
    estoque_minima = models.FloatField(default=0, verbose_name="Quantidade Minima")
    fornecedor = models.ForeignKey(EmpresaContratante, on_delete=models.CASCADE, blank=True, null=True)

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'material': self.nome,
            'estoque': self.estoque,
            'preco': self.preco,
        }

    def __str__(self):
        return self.codigo + ' - ' + self.nome + ' -  R$ ' + str(self.preco)

    def get_absolute_url(self):
        return reverse('listar_material')

apps/material/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

from apps.material.models import MaterialEstoque


class FormMaterial(BSModalForm):
    class Meta:
        model = MaterialEstoque
        fields = ('codigo', 'nome', 'estoque', 'preco', 'estoque_minima', 'fornecedor')
        widgets = {
            'codigo':forms.TextInput(attrs={'class': 'form-control', 'required': 'false', 'readonly': 'readonly'}),
            'estoque': forms.TextInput(attrs={'class': 'form-control', 'required': 'false', 'readonly': 'readonly'})
        }

apps/material/views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from apps.material.forms import FormMaterial
from apps.material.models import MaterialEstoque
from apps.material.uteis import Util


@method_decorator([login_required], name='dispatch')
class CreateMaterial(BSModalCreateView):
    success_url = reverse_lazy('listar_material')
    form_class = FormMaterial
    template_name = "cadastrar_material.html"

    def get_context_data(self, **kwargs):
        context = super(CreateMaterial, self).get_context_data(**kwargs)
        context['codigo_mat'] = Util.geradorcodigo()
        return context


@method_decorator([login_required], name='dispatch')
class UpdateMaterial(BSModalUpdateView):
    model = MaterialEstoque
    template_name = 'atualizar_material.html'
    form_class = FormMaterial
    success_url = reverse_lazy('listar_material')



@method_decorator([login_required], name='dispatch')
class ListMaterial(ListView):
    model = MaterialEstoque
    template_name = "listar_material.html"
    context_object_name = "object_list"
    paginate_by = 10



@login_required()
def material_json(request, pk):
    ''' Retorna o material, id e estoque. '''
    material = MaterialEstoque.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in material]
    return JsonResponse({'data': data})


apps/material/templates/atualizar_material.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title" style="text-align: center;">Atualizar Material</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    <div class="form-group">
      <label for="{{ form.id_for_label }}">{{ form.codigo.label }}</label>
      {% render_field form.codigo class="form-control" placeholder=form.codigo.label %}


      <label for="{{ form.id_for_label }}">{{ form.nome.label }}</label>
      {% render_field form.nome class="form-control" placeholder=form.nome.label %}
      <div class="{% if form.nome.errors %} invalid{% endif %}">
        {% for error in form.nome.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.estoque.label }}</label>
      {% render_field form.estoque class="form-control" placeholder=form.estoque.label %}

      <label for="{{ form.id_for_label }}">{{ form.preco.label }}</label>
      {% render_field form.preco class="form-control" placeholder=form.preco.label %}
      <div class="{% if form.preco.errors %} invalid{% endif %}">
        {% for error in form.preco.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.estoque_minima.label }}</label>
      {% render_field form.estoque_minima class="form-control" placeholder=form.estoque_minima.label %}
      <div class="{% if form.estoque_minima.errors %} invalid{% endif %}">
        {% for error in form.estoque_minima.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.fornecedor.label }}</label>
      {% render_field form.fornecedor class="form-control" placeholder=form.fornecedor.label %}

    </div>

  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Atualizar</button>
  </div>
</form>

apps/material/templates/cadastrar_material.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title" style="text-align: center;">Cadastrar Material</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    <div class="form-group">
      <label for="{{ form.id_for_label }}">{{ form.codigo.label }}</label>
      <input type="text" name="codigo" maxlength="100" value="{{ codigo_mat }}" readonly="true" class="form-control" required="" id="id_codigo">

      <label for="{{ form.id_for_label }}">{{ form.nome.label }}</label>
      {% render_field form.nome class="form-control" placeholder=form.nome.label %}
      <div class="{% if form.nome.errors %} invalid{% endif %}">
        {% for error in form.nome.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.estoque.label }}</label>
      {% render_field form.estoque class="form-control" placeholder=form.estoque.label %}

      <label for="{{ form.id_for_label }}">{{ form.preco.label }}</label>
      {% render_field form.preco class="form-control" placeholder=form.preco.label %}
      <div class="{% if form.preco.errors %} invalid{% endif %}">
        {% for error in form.preco.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.estoque_minima.label }}</label>
      {% render_field form.estoque_minima class="form-control" placeholder=form.estoque_minima.label %}
      <div class="{% if form.estoque_minima.errors %} invalid{% endif %}">
        {% for error in form.estoque_minima.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      <label for="{{ form.id_for_label }}">{{ form.fornecedor.label }}</label>
      {% render_field form.fornecedor class="form-control" placeholder=form.fornecedor.label %}

    </div>

  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Atualizar</button>
  </div>
</form>

apps/material/templates/listar_material.html
{% extends 'base.html' %}
{% block title %}Lista de Materiais{% endblock %}

{% block content %}
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Materiais</h1>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<section class="content">
  <div class="container-fluid">
    <div class="card card-default">
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <button class="create-material btn btn-outline-primary">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    Adicionar
                </button>
            </div>
            <div class="col-lg-10" style="text-align: right;">
                <div class="col-md-4 float-right">
                    <div class="input-group input-group">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Pesquisar">

                        <div class="input-group-append">
                          <button type="submit" class="btn btn-outline-primary"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content">
  <div class="container-fluid">
      <!-- /.card-header -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Código</th>
                                <th>Descrição</th>
                                <th style="text-align: center;">Qtd. Entrada</th>
                                <th style="text-align: center;">Qtd. Saída</th>
                                <th style="text-align: center;">Qtd. Estoque</th>
                                <th>Fornecedor</th>
                                <th style="width: 8%; text-align: center;">Ação</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for material in object_list %}
                                <tr>
                                    <td>{{ material.codigo }}</td>
                                    <td>{{ material.nome }}</td>
                                    <td></td>
                                    {% for m in material.itensestoque_set.all %}
                                    {% if m.estoque.movimento == 's'  %}

                                    {% endif %}
                                    {% endfor %}
                                    <td></td>
                                    {% if material.estoque > material.estoque_minima %}
                                        <td style="text-align: center;">{{ material.estoque }}</td>
                                    {% else %}
                                        <td style="text-align: center; background-color:red;">{{ material.estoque }}</td>
                                    {% endif %}
                                    <td></td>
                                    <td style="width: 10%; text-align: center">
                                        <button class="update-material btn btn-cust-danger btn-xs"
                                                data-id="{% url 'atualizar_material' material.pk %}">
                                            <i class="fa fa-edit" title="Editar"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
  </div>
</section>
{% include "parts/pagination.html" %}
{% endblock %}